### ISSUE TITLE
IVs attribute error

### ISSUE THREAD

**Issue by aditya1000** [pronobis/libspn#86]
Getting error, module 'libspn' has no attribute 'IVs'
![libspn error](https://user-images.githubusercontent.com/15032629/66858497-0856e480-efa7-11e9-89ad-8e3027044bc4.PNG)

**Comment by gennartan** [comment]
I have the same issue as you. It seems that the keywork "IVs" was replaced by "IndicatorLeaf" in a previous merge request. Also the keyword "generate_ivs" was replaced by "generate_latent_indicators".
`iv_x = libspn.IndicatorLeaf(num_vars=2, num_vals=2, name="iv_x")`
`iv_y = root.generate_latent_indicators(name="iv_y") # Can be added manually`

There are also other problems that comes after making these change. I would advise you to manually build the library from a previous version of the git repository.

**Comment by jostosh** [comment]
Hi @aditya1000 and @gennartan, thanks for checking out the library and informing us about the issue.  The instructions on `libspn.org` are indeed outdated. I will upload the updated version in a few hours. Apologies for not getting back to you before, I was off on holiday for a while.

As @gennartan pointed out correctly, `IVs` were replaced by `IndicatorLeaf` and `generate_ivs` was replaced by `generate_latent_indicators`. Also the `init_value` argument in `generate_weights` is replaced by `intializer` and it takes a standard TensorFlow initializer from `tf.initializers.*`.

**Comment by jostosh** [comment]
Tutorials on `libspn.org` have been updated
