### ISSUE TITLE
log probability for all classes given an observation

### ISSUE THREAD

**Issue by anicolson** [pronobis/libspn#90]
Hi, for tutorial 7, I was wondering which node from the graph I should give to sess.run() to get the log probability of each class given an observation. 

E.g. for 32 observations from the MNIST set: 
the size of batch_x is [32,784]. I want output of sess.run() to be of size [32,10], where these are the log probabilities of each of the 10 classes.

Thank you very much!

**Comment by jostosh** [comment]
Hi, there's this part:

```
class_roots = spn.ParallelSums(full_scope_prod, num_sums=num_classes)
root = spn.Sum(class_roots)
```
You can add something along these lines:
```
log_p_x_given_y = class_roots.get_log_value()
log_p_y = root.weights.node.get_log_value()
log_p_x = root.get_log_value()

# Good ol' Bayes rule: p(y|x) == p(x|y)p(y)/p(x)
log_p_y_given_x = (log_p_x_given_y + log_p_y) - log_p_x
p_y_given_x = tf.exp(log_p_y_given_x)
```
Not near a computer now so cannot test right now, but this should be close to the answer

**Comment by anicolson** [comment]
Thank you! I'll give it a try
